version: '3.5'

services:
    app:
        image: node:${NODE_VERSION:-latest}
        volumes:
            - ${NODE_DATA_DIR:-./}:/app
        working_dir: /app
        ports:
            - ${NODE_PORT:-3000}:3000
        command: >
            sh -c "npm install && npm start"
        tty: true
